filegroup(
	name = "assets",
	visibility = ["//visibility:public"],
	srcs = [
		"diablo3_pose.obj",
		"diablo3_pose.tga",
		"diablo3_pose_nm.tga",
		"diablo3_pose_spec.tga",
		"teapot.obj",
		"head.obj",
		"head.tga",
		"head_nm.tga",
		"head_spec.tga",
		"head_eye_inner.obj",
		"head_eye_inner_diffuse.tga",
	],
)
